name: Calculadora Secuencial Paralela
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Node.js y pnpm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          corepack enable
          corepack prepare pnpm@latest --activate
          
  pruebas-paralelas:
      runs-on: ubuntu-latest
      needs: build
      strategy:
        matrix:
          operacion: [sumar, restar]
      steps:
        - uses: actions/checkout@v4
        - name: Ejecutar operacion ${{matrix.operacion}}
          run: |
            echo 'const calc = require("./calculadora"); console.log("Resultado de ${{ matrix.operacion }}:", calc.${{ matrix.operacion }}(5,2));' > test.js
            node test.js
          
  reporte-final:
     runs-on: ubuntu-latest
     needs: pruebas-paralelas
     steps:
       - uses:  actions/checkout@v4
       - name: Mostrar mensaje final
         run: echo "Todas las operaciones de calculadora se ejecutaron correctamente"
   
