name: saludo
on:
  workflow_dispatch
    
jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar saludo
        run: echo "Hola Tú"
      - name: Mostrar ubicación actual del runner
        run: pwd
      - name: Listar archivos en el directorio actual
        run: ls -la
